<?php

return [
    "title" => "数据库管理",
    "url" => "admin/database/index",
    "method" => "GET",
    "slug" => $this->slug,
    "icon" => "icon-bangzhushouce",
    "listorder" => 100,
    "menu_show" => 1,
    "remark" => "",
    "children" => [
        [
            "title" => "数据库备份",
            "url" => "admin/database/index",
            "method" => "GET",
            "slug" => "admin.database.index",
            "icon" => "icon-bangzhushouce",
            "listorder" => 5,
            "menu_show" => 1,
            "children" => [
                [
                    "title" => "修复表",
                    "url" => "admin/database/repair",
                    "method" => "POST",
                    "slug" => "admin.database.repair-post",
                    "menu_show" => 0,
                ],
                [
                    "title" => "优化表",
                    "url" => "admin/database/optimize-post",
                    "method" => "POST",
                    "slug" => "admin.database.optimize",
                    "menu_show" => 0,
                ],
                [
                    "title" => "还原表",
                    "url" => "admin/database/import",
                    "method" => "GET",
                    "slug" => "admin.database.import",
                    "menu_show" => 0,
                ],
                [
                    "title" => "备份数据库",
                    "url" => "admin/database/export",
                    "method" => "GET",
                    "slug" => "admin.database.export",
                    "menu_show" => 0,
                ],
                [
                    "title" => "备份数据库",
                    "url" => "admin/database/export-post",
                    "method" => "POST",
                    "slug" => "admin.database.export",
                    "menu_show" => 0,
                ],
            ],
        ],
        [
            "title" => "数据库还原",
            "url" => "admin/database/restore",
            "method" => "GET",
            "slug" => "admin.database.restore",
            "menu_show" => 1,
            "icon" => "icon-undo",
            "listorder" => 10,
            "child" => [
                [
                    "title" => "数据库还原",
                    "url" => "admin/database/restore",
                    "method" => "GET",
                    "slug" => "admin.database.restore",
                    "menu_show" => 0,
                ],
                [
                    "title" => "备份数据库",
                    "url" => "admin/database/restore",
                    "method" => "POST",
                    "slug" => "admin.database.restore-post",
                    "menu_show" => 0,
                ],
                [
                    "title" => "删除备份",
                    "url" => "admin/database/del",
                    "method" => "POST",
                    "slug" => "admin.database.del-post",
                    "menu_show" => 0,
                ],
                [
                    "title" => "备份数据库下载",
                    "url" => "admin/database/download",
                    "method" => "GET",
                    "slug" => "admin.database.download",
                    "menu_show" => 0,
                ],
            ],
        ],
    ],
];
