<?php

return [
    "title" => "数据库管理",
    "url" => "database/index",
    "method" => "GET",
    "slug" => $slug,
    "icon" => "icon-bangzhushouce",
    "listorder" => 1065,
    "menu_show" => 1,
    "remark" => "",
    "children" => [
        [
            "title" => "数据管理",
            "url" => "database/index",
            "method" => "GET",
            "slug" => "admin.database.index",
            "icon" => "icon-bangzhushouce",
            "listorder" => 15,
            "menu_show" => 1,
            "children" => [
                [
                    "title" => "数据管理",
                    "url" => "database/index",
                    "method" => "GET",
                    "slug" => "admin.database.index",
                    "menu_show" => 0,
                    "listorder" => 15,
                ],
                [
                    "title" => "数据列表",
                    "url" => "database/index",
                    "method" => "POST",
                    "slug" => "admin.database.index-post",
                    "menu_show" => 0,
                    "listorder" => 14,
                ],
                [
                    "title" => "修复表",
                    "url" => "database/repair",
                    "method" => "POST",
                    "slug" => "admin.database.repair-post",
                    "menu_show" => 0,
                    "listorder" => 13,
                ],
                [
                    "title" => "优化表",
                    "url" => "database/optimize",
                    "method" => "POST",
                    "slug" => "admin.database.optimize-post",
                    "menu_show" => 0,
                    "listorder" => 12,
                ],
                [
                    "title" => "备份数据库",
                    "url" => "database/export",
                    "method" => "GET",
                    "slug" => "admin.database.export",
                    "menu_show" => 0,
                    "listorder" => 11,
                ],
                [
                    "title" => "备份数据库",
                    "url" => "database/export",
                    "method" => "POST",
                    "slug" => "admin.database.export-post",
                    "menu_show" => 0,
                    "listorder" => 10,
                ],
            ],
        ],
        [
            "title" => "备份列表",
            "url" => "database/restore",
            "method" => "GET",
            "slug" => "admin.database.restore",
            "menu_show" => 1,
            "icon" => "icon-jifen",
            "listorder" => 10,
            "children" => [
                [
                    "title" => "备份列表",
                    "url" => "database/restore",
                    "method" => "GET",
                    "slug" => "admin.database.restore",
                    "menu_show" => 0,
                    "listorder" => 15,
                ],
                [
                    "title" => "备份列表",
                    "url" => "database/restore",
                    "method" => "POST",
                    "slug" => "admin.database.restore-post",
                    "menu_show" => 0,
                    "listorder" => 14,
                ],
                [
                    "title" => "删除备份",
                    "url" => "database/del",
                    "method" => "POST",
                    "slug" => "admin.database.del-post",
                    "menu_show" => 0,
                    "listorder" => 13,
                ],
                [
                    "title" => "还原表",
                    "url" => "database/import",
                    "method" => "GET",
                    "slug" => "admin.database.import",
                    "menu_show" => 0,
                    "listorder" => 12,
                ],
                [
                    "title" => "备份数据库下载",
                    "url" => "database/download",
                    "method" => "GET",
                    "slug" => "admin.database.download",
                    "menu_show" => 0,
                    "listorder" => 11,
                ],
            ],
        ],
    ],
];
